spring.application.name=library_management_system
spring.profiles.active=dev

# Logging configuration
logging.level.com.project.library_management_system.aspect=DEBUG
logging.level.org.springframework=ERROR